### ISSUE TITLE
It's too slow

### ISSUE THREAD

**Issue by matthewyan** [tapwork/HeapInspector-for-iOS#10]
In my app, I record the memory usage, but it too slow. 
One operation may cost ten minutes.

If run for a while, the app may killed because the memory:Message from debugger: Terminated due to Memory Error
I Test this in iPhone 6 & iphone 5c.  The project is large and many objects are alloced when running.

somebody has the same problem? how should I resolve this. Thanks!

**Comment by tapwork** [comment]
Did you try turning off the backtrace record?
`[HINSPDebug recordBacktraces:NO];`

**Comment by tapwork** [comment]
Should be better now with `0.2.0` https://github.com/tapwork/HeapInspector-for-iOS/releases/tag/0.2.0

**Comment by matthewyan** [comment]
:+1:  Yeah, I have used this version, It's better. thank you

**Comment by tapwork** [comment]
So I can close this issue for now
