### ISSUE TITLE
HeapInspectorExample crash

### ISSUE THREAD

**Issue by 52doho** [tapwork/HeapInspector-for-iOS#12]
1. Check out code with tag 0.0.6, and run the HeapInspectorExample.
2. Tap Record button and Gallery button.
It crash in NSObject+HeapInspector.m, Line 152, EXC_BAD_ACCESS.

BTW, it seams this was introduced in commit: 45fb730. The param backtrace is released in getBacktrace().

**Comment by tapwork** [comment]
that's weird...tests are green and also runs here...
but I have a look
