### ISSUE TITLE
Confuse on Retain Count

### ISSUE THREAD

**Issue by zzaiguo** [tapwork/HeapInspector-for-iOS#15]
I am confused by the algorithm of Retain Count.
in HeapInspector,Retain Count = alloc+retain+strong -release, but is not always equals to CFGetRetainCount((__bridge CFTypeRef)object), why?

**Comment by tapwork** [comment]
hard so answer right now...
do you have an example snippet?

**Comment by tapwork** [comment]
Since the new version `0.2.0` now uses `CFGetRetainCount`, I'd close this issue
