### ISSUE TITLE
Support module instead of class prefix

### ISSUE THREAD

**Issue by tbaranes** [tapwork/HeapInspector-for-iOS#18]
Since swift isn't using prefix anymore, it's really hard our own objects. I can think two solutions to make it working with this kind of projects:
- Filtering using the project module instead of using a simple prefix 
- Add a search field which can make easier to track our own objects

**Comment by tapwork** [comment]
Thanks for the feedback...I am aware of this prefix issue.
Check modules would be nice. I could tackle that the next weeks.. 
but there is actually a search field in the inspector.

**Comment by tbaranes** [comment]
Yeah, I find this out after posting my issue, but even with the search field, it's pretty hard to get our swift objects since they don't have anything in common to find them back :cry:

**Comment by tapwork** [comment]
HeapInspector needs definitely some improvements for Swift.
It's on the road map.
Hopefully done until end of March

**Comment by tapwork** [comment]
@tbaranes the latest changes on master here include a recording for Swift modules now. Have a look and tell me what you think.

**Comment by tapwork** [comment]
Now fixed with https://github.com/tapwork/HeapInspector-for-iOS/releases/tag/0.2.0

**Comment by tbaranes** [comment]
Just tried it, it works perfectly :tada:

**Comment by tapwork** [comment]
:+1:
