### ISSUE TITLE
crash when stopRecord

### ISSUE THREAD

**Issue by liumeng0917** [tapwork/HeapInspector-for-iOS#21]
<img width="1069" alt="2016-10-21 2 48 03" src="https://cloud.githubusercontent.com/assets/5424453/19589211/86176396-979d-11e6-9b6d-2c38e5e83261.png">
<img width="1091" alt="2016-10-21 2 48 21" src="https://cloud.githubusercontent.com/assets/5424453/19589216/8df32014-979d-11e6-9065-3f3949b40576.png">

**Comment by tapwork** [comment]
@liumeng0917 can you provide an example project to reproduce the issue?
