### ISSUE TITLE
Non-GUI example

### ISSUE THREAD

**Issue by rlaferla** [tapwork/HeapInspector-for-iOS#9]
Can you show how this could be used without a GUI? e.g..  in app extensions that can't display a full UI?  A simple way using NSLog() would be much appreciated.

**Comment by tapwork** [comment]
Right now I don't have a Non-GUI support.
But it's a good idea. Also HeapInspector could throw exceptions or at least run some NSAsserts

**Comment by tapwork** [comment]
I have some updates how you could use HeapInspector without GUI.
Have a look the Example's test classes how

**Comment by tapwork** [comment]
like this
```
    [HINSPDebug startWithClassPrefix:@"UITableView"];
    [HINSPDebug recordBacktraces:YES];
    [NSObject beginSnapshotWithClassPrefix:@"UITableView"];
    self.tableView = [[UITableView alloc] init];   
    NSArray *refHistory = [NSObject referenceHistoryForObject:self.tableView];
```
